// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-SM8xgrTxREtSZCVD2MmfkI8ZT2GmVA',
    appId: '1:940255703825:android:4db679798beadd09b492b0',
    messagingSenderId: '940255703825',
    projectId: 'quitsmokingclub-ded45',
    storageBucket: 'quitsmokingclub-ded45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-SM8xgrTxREtSZCVD2MmfkI8ZT2GmVA',
    appId: '1:940255703825:ios:quitsmokingclub',
    messagingSenderId: '940255703825',
    projectId: 'quitsmokingclub-ded45',
    storageBucket: 'quitsmokingclub-ded45.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-SM8xgrTxREtSZCVD2MmfkI8ZT2GmVA',
    appId: '1:940255703825:macos:quitsmokingclub',
    messagingSenderId: '940255703825',
    projectId: 'quitsmokingclub-ded45',
    storageBucket: 'quitsmokingclub-ded45.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW-SM8xgrTxREtSZCVD2MmfkI8ZT2GmVA',
    appId: '1:940255703825:windows:quitsmokingclub',
    messagingSenderId: '940255703825',
    projectId: 'quitsmokingclub-ded45',
    storageBucket: 'quitsmokingclub-ded45.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAW-SM8xgrTxREtSZCVD2MmfkI8ZT2GmVA',
    appId: '1:940255703825:linux:quitsmokingclub',
    messagingSenderId: '940255703825',
    projectId: 'quitsmokingclub-ded45',
    storageBucket: 'quitsmokingclub-ded45.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-SM8xgrTxREtSZCVD2MmfkI8ZT2GmVA',
    appId: '1:940255703825:web:75dd3c3c2407b02db492b0',
    messagingSenderId: '940255703825',
    projectId: 'quitsmokingclub-ded45',
    authDomain: 'quitsmokingclub-ded45.firebaseapp.com',
    storageBucket: 'quitsmokingclub-ded45.firebasestorage.app',
    measurementId: 'G-0000000000',
  );
}
